spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: atlassian-connect-spring-boot-sample-atlaskit
  base-url: https://atlas-connect-test.onrender.com

logging.level.com.atlassian.connect.spring: DEBUG

atlassian:
  connect:
    require-auth-exclude-paths: [/issue, /issue/create]
